(defun masse-light ()
  (interactive)
  (color-theme-install
   '(masse-light
      ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "#000000")
      (cursor-color . "#d7dc09")
      (foreground-color . "#000000")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#fafafa" :background "#fa0f0f"))))
     (region ((t (:background "#a1e3ec"))))
     (font-lock-builtin-face ((t (:foreground "#78238b"))))
     (font-lock-comment-face ((t (:foreground "#f62c2c"))))
     (font-lock-function-name-face ((t (:foreground "#210df8"))))
     (font-lock-keyword-face ((t (:foreground "#415d19"))))
     (font-lock-string-face ((t (:foreground "#ef9106"))))
     (font-lock-type-face ((t (:foreground"#47068e"))))
     (font-lock-variable-name-face ((t (:foreground "#99622e"))))
     (minibuffer-prompt ((t (:foreground "#fb1e13" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'masse-light)
