#! /bin/sh

set_="VBoxManage setextradata"
config_ssh="VBoxInternal/Devices/pcnet/0/LUN#0/Config/ssh"

if [ -z "$1" ]; then
    $set_ $1 "$config_ssh/Protocol" TCP
    $set_ $1 "$config_ssh/GuestPort" 22
    $set_ $1 "$config_ssh/HostPort" 2222
fi
